on: [push]
name: "Tests and Publish"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: go test -cover ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lol3r/strat-roulette-backend:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: lol3r.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: docker pull lol3r/strat-roulette-backend:latest && cd personal_compose/ && docker-compose up -d